# Registries defined within cri-o.
# crio_insecure_registries:
#   - 10.0.0.2:5000

# Auth config for the registries
# crio_registry_auth:
#   - registry: 10.0.0.2:5000
#     username: user
#     password: pass
crio_registries:
  - prefix: docker.io
    insecure: false
    blocked: false
    location: docker.io
    unqualified: true
  - prefix: quay.io
    insecure: false
    blocked: false
    location: quay.io
    unqualified: true

crio_unqualified_search_registries:
  - docker.io
  - quay.io
  - gcr.io
